synonyms = {
       'cal': 'california', 
       'wichita st.': 'wichita state',
       'miami': 'miami (fl)', 
       "saint joe's": "saint joseph's",
       'unc': 'north carolina',
       'usc': 'southern california',
       'uva': 'virginia',
       'uconn': 'connecticut',
       's. dakota st.': 'south dakota state',
       'unc-wilm.': 'north carolina-wilmington',
       'n. iowa': 'northern iowa',
       'vcu': 'virginia commonwealth',
       'chatt.': 'chattanooga',
       'w. virginia': 'west virginia',
       'ark.-lr': 'arkansas-little rock',
       'virginia com': 'virginia commonwealth',
       'north caroli': 'north carolina',
       'west virgini': 'west virginia',
       'michigan sta': 'michigan state',
       'south dakota': 'south dakota state',
       'wichita stat': 'wichita state',
       'northern iow': 'northern iowa',
       'stephen f. a': 'stephen f. austin',
       'arkansas-lit': 'arkansas-little rock',
       'southern cal': 'southern california',
        'florida gulf': 'florida gulf coast',
       'n. c. wilmington': 'north carolina-wilmington',
       'fresno st.': 'fresno state',
       'n. carolina': 'north carolina',
       'ar little rock': 'arkansas-little rock',
       'iowa st.': 'iowa state',
       'michigan st.': 'michigan state',
       'sf austin': 'stephen f. austin',
       'wichita st': 'wichita state',
       'n carolina': 'north carolina',
       'michigan st': 'michigan state',
       'oregon st.': 'oregon state',
       'n.c. wilmington': 'north carolina-wilmington',
       's.f. austin': 'stephen f. austin',
       "st. joseph\\'s": "saint joseph's",
       "texas am": "texas a&m",
       "saint joes": "saint joseph's",
       "pitt": "pittsburgh",
       "ky": "kentucky",
       "mich st": "michigan state",
       "okla": "oklahoma",
       "west v": "west virginia",
       "nova": "villanova",
       "iowa st": "iowa state",
       "ar-little rock": "arkansas-little rock",
       "zona": "arizona",
       "oregon st": "oregon state",
       "unc wilmington": "north carolina-wilmington",
       "unc-wilm": "north carolina-wilmington",
       "fgcu": "florida gulf coast",
       "unc-ash.": "north carolina-asheville",
       "csu bakers.": "cal state bakersfield",
       "mid. tenn.": "middle tennessee",
       "saint joseph": "saint joseph's", 
       "saint mary\\'s": "saint mary's (ca)",
       "saint mary's": "saint mary's (ca)",
       "southern met": "southern methodist",
       "south caroli": "south carolina",
       "new mexico s": "new mexico state",
       "virginia tec": "virginia tech", 
       "northern ken": "northern kentucky", 
       "florida stat": "florida state",
       "middle tenne": "middle tennessee",
       "oklahoma sta": "oklahoma state",
       "east tenness": "east tennessee state",
       "jacksonville": "jacksonville state",
       "texas southe": "texas southern",
       "mount st. ma": "mount st. mary's",
       "florida st.": "florida state",
       "smu": "southern methodist",
       "middle tenn. st.": "middle tennessee",
       "fla gulf coast": "florida gulf coast",
       "e. tennessee st.": "east tennessee state",
       "kansas st.": "kansas state",
       "n. mex. st.": "new mexico state",
       "st. mary\\'s": "saint mary's (ca)",
       "oklahoma st.": "oklahoma state",

       # 2019
       "mississippi st.": "mississippi state",
       "lsu": "louisiana state",
       "utah st.": "utah state",
       "ucf": "central florida",
       "arizona st.": "arizona state",
       "uc irvine": "uc-irvine",
       "murray st.": "murray state",
       "ohio st.": "ohio state",
       "georgia st.": "georgia state",
       "north. kentucky": "northern kentucky",
       "nm state": "new mexico state",
       "nd state": "north dakota state",
       "abilene": "abilene christian",
       "f. dickinson": "fairleigh dickinson",
       "st. mary's": "saint mary's (ca)",
       "miss. state": "mississippi state",
       # "": "",
       # "": "",
       # "": "",
       # "": "",
       }